#include "builtin.hpp"
#include "util.hpp"
#include <cstddef>

namespace dcap {
namespace {

// One embedded template file. `size` is the exact byte count — the generated
// arrays carry a trailing 0 so an empty file stays a valid initialiser, and
// carrying the length separately means content with embedded NULs survives.
struct Entry {
    const char* path; // relative to the template root
    const unsigned char* data;
    std::size_t size;
};

// One built-in template, i.e. one directory under templates/.
struct Template {
    const char* name;
    const Entry* files;
    std::size_t count;
};

// Generated by tools/gen-embed.sh from templates/: a namespace per template
// directory, plus kTemplates[] tying them together. Nothing here names a
// specific template, so adding one is purely a matter of adding the directory.
#include "builtin_tables.inc"

const Template* find_template(const std::string& name) {
    for (const Template& t : kTemplates)
        if (name == t.name)
            return &t;
    return nullptr;
}

} // namespace

bool is_builtin(const std::string& name) {
    return find_template(name) != nullptr;
}

std::string builtin_names() {
    std::string out;
    for (const Template& t : kTemplates) {
        if (!out.empty())
            out += " | ";
        out += t.name;
    }
    return out;
}

bool write_builtin(const std::string& name, const std::string& dest) {
    const Template* t = find_template(name);
    if (!t)
        return false;
    bool ok = true;
    for (std::size_t i = 0; i < t->count; ++i) {
        const Entry& e = t->files[i];
        const std::string out = dest + "/" + e.path;
        ok = ensure_parent_dir(out) && ok;
        ok = write_file(out, std::string(reinterpret_cast<const char*>(e.data),
                                         e.size)) &&
             ok;
    }
    return ok;
}

} // namespace dcap
