#!/bin/sh
# Emit the whole built-in template registry — the Makefile writes it to
# build/builtin_tables.inc and src/builtin.cpp #includes it.
#
# Every directory under templates/ that looks like a template (same rule dcap
# uses at runtime: it contains a Makefile) becomes a built-in. Adding one means
# creating the directory — no C++, no Makefile, no edit here.
#
# Only regular files are listed, so an empty directory inside a built-in
# template would not survive; put a .gitkeep in it, as the external-template
# path does.
set -eu

root=templates
[ -d "$root" ] || { echo "gen-embed: no $root/ directory" >&2; exit 1; }

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

# Template directories, stable order. A directory without a Makefile is not a
# template — say so rather than silently shipping something unusable.
list_dirs() {
    for d in "$root"/*/; do
        [ -d "$d" ] || continue
        n=${d#"$root"/}
        n=${n%/}
        if [ -f "$d/Makefile" ] || [ -f "$d/makefile" ]; then
            printf '%s\n' "$n"
        else
            echo "gen-embed: skipping $root/$n (no Makefile)" >&2
        fi
    done | LC_ALL=C sort
}

# Paths relative to a template's root, stable order so the generated file only
# changes when the templates do.
list_files() { (cd "$root/$1" && find . -type f | sed 's|^\./||' | LC_ALL=C sort); }

dirs=$(list_dirs)
[ -n "$dirs" ] || { echo "gen-embed: no templates found under $root/" >&2; exit 1; }

# Quotes and backslashes would break the C++ string literals below; whitespace
# would break the shell loops. Fail loudly rather than emitting broken code.
for t in $dirs; do
    if list_files "$t" | grep -q '["\\]'; then
        echo "gen-embed: file names must not contain quotes or backslashes ($root/$t)" >&2
        exit 1
    fi
done
if printf '%s\n' "$dirs" | grep -q '[[:space:]]'; then
    echo "gen-embed: template directory names must not contain whitespace" >&2
    exit 1
fi

printf '// Generated by tools/gen-embed.sh from %s/ — do not edit.\n' "$root"
printf '// #embed paths are relative to this file, which lives in build/.\n'

# One namespace per template. Each array carries a trailing 0 so that an empty
# file is still a valid initialiser; the exact byte count goes in the table, so
# content with embedded NULs survives too.
i=0
for t in $dirs; do
    list_files "$t" > "$tmp"
    printf '\nnamespace tpl%d {  // %s/%s\n' "$i" "$root" "$t"
    n=0
    while IFS= read -r f; do
        printf 'constexpr unsigned char kE%d[] = {\n' "$n"
        if [ -s "$root/$t/$f" ]; then
            printf '#embed "../%s/%s/%s"\n, 0};\n' "$root" "$t" "$f"
        else
            printf '0};  // empty file\n'
        fi
        n=$((n + 1))
    done < "$tmp"
    printf 'constexpr Entry kEntries[] = {\n'
    n=0
    while IFS= read -r f; do
        printf '    {"%s", kE%d, sizeof kE%d - 1},\n' "$f" "$n" "$n"
        n=$((n + 1))
    done < "$tmp"
    printf '};\n}  // namespace tpl%d\n' "$i"
    i=$((i + 1))
done

printf '\nconstexpr Template kTemplates[] = {\n'
i=0
for t in $dirs; do
    printf '    {"%s", tpl%d::kEntries, sizeof tpl%d::kEntries / sizeof(Entry)},\n' \
        "$t" "$i" "$i"
    i=$((i + 1))
done
printf '};\n'
