from __future__ import annotations

import hashlib
import copy
import unittest
from unittest import mock

from p1a2_model import root_call_bytes
from p1a2_store import Corruption, canonical_json, make_ref, root_id, strict_json, task_id
from test_support import root_call


# Checked-in literals.  They are intentionally not generated by the production
# canonicalizer on the expected side of each assertion.
ROOT_CALL_BYTES = (b'{"children":[{"recipe":{"argv":["/opt/aos-fixture/process","success",'
                   b'"/work/aos"],"cwd":"/work/aos","definition_path":"/opt/aos-fixture/process",'
                   b'"environment_policy":{"kind":"inherit"},"kind":"process","stdin":'
                   b'{"data":"AP8=","encoding":"base64"}},"slot":"first"},{"recipe":{"kind":'
                   b'"fake","result":{"stderr":{"data":"","encoding":"base64"},"stdout":'
                   b'{"data":"U0VDT05ECg==","encoding":"base64"},"termination":{"code":0,"kind":'
                   b'"exited"}}},"slot":"second"}],"first_success_oracle":{"stderr":{"data":'
                   b'"","encoding":"base64"},"stdout":{"data":"UDFBMi1ERVRFUk1JTklTVElDLU9LCg==",'
                   b'"encoding":"base64"},"termination":{"code":0,"kind":"exited"}},"kind":'
                   b'"sequence_two","v":1}\n')
ROOT_CALL_SHA256 = "12d8b762806401320f7721748a0f6b9bf71529fa3c082137f16c3a7d3d64a8e0"
ROOT_PLANNED_LINE = (b'{"call_ref":{"sha256":"12d8b762806401320f7721748a0f6b9bf71529fa3c082137f16c3a7d3d64a8e0",'
                     b'"size":662},"root_id":"root","type":"root_planned","v":1}\n')
ROOT_LINKED_LINE = (b'{"call_ref":{"sha256":"12d8b762806401320f7721748a0f6b9bf71529fa3c082137f16c3a7d3d64a8e0",'
                    b'"size":662},"root_id":"root","type":"root_linked","v":1}\n')
ACCEPTED_LINE = b'{"type":"accepted","v":1}\n'
TASK_BYTES = (b'{"call_ref":{"sha256":"12d8b762806401320f7721748a0f6b9bf71529fa3c082137f16c3a7d3d64a8e0",'
              b'"size":662},"task_id":"root","v":1}\n')


class GoldenVectors(unittest.TestCase):
    def test_root_call_exact_bytes_and_ref(self):
        actual = root_call_bytes(root_call())
        self.assertEqual(actual, ROOT_CALL_BYTES)
        self.assertEqual(hashlib.sha256(actual).hexdigest(), ROOT_CALL_SHA256)
        self.assertEqual(make_ref(actual), {"sha256": ROOT_CALL_SHA256, "size": len(ROOT_CALL_BYTES)})

    def test_root_event_exact_lines(self):
        ref = {"sha256": ROOT_CALL_SHA256, "size": len(ROOT_CALL_BYTES)}
        self.assertEqual(canonical_json({"v": 1, "type": "root_planned", "root_id": "root", "call_ref": ref}), ROOT_PLANNED_LINE)
        self.assertEqual(canonical_json({"v": 1, "type": "root_linked", "root_id": "root", "call_ref": ref}), ROOT_LINKED_LINE)
        self.assertEqual(canonical_json({"v": 1, "type": "accepted"}), ACCEPTED_LINE)
        self.assertEqual(canonical_json({"v": 1, "task_id": "root", "call_ref": ref}), TASK_BYTES)

    def test_strict_json_rejects_duplicate_float_trailing_and_bad_unicode(self):
        bad = (
            b'{"v":1,"v":1}', b'{"v":1.0}', b'{"v":NaN}',
            b'{"v":1} trailing', b'\xff', b'{"v":"\\ud800"}',
        )
        for data in bad:
            with self.subTest(data=data), self.assertRaises(Corruption):
                strict_json(data, "negative vector")

    def test_root_call_exact_schema_negative_vectors(self):
        cases = []
        def changed(mutator):
            value = copy.deepcopy(root_call()); mutator(value); cases.append(value)
        changed(lambda x: x.__setitem__("v", True))
        changed(lambda x: x.__setitem__("extra", 1))
        changed(lambda x: x["children"].reverse())
        changed(lambda x: x["children"][0]["recipe"].__setitem__("definition_path", "relative"))
        changed(lambda x: x["children"][0]["recipe"].__setitem__("argv", []))
        changed(lambda x: x["children"][0]["recipe"].__setitem__("environment_policy", {"kind": "other"}))
        changed(lambda x: x["children"][0]["recipe"]["stdin"].__setitem__("data", "AP8"))
        changed(lambda x: x["first_success_oracle"]["termination"].__setitem__("code", 1))
        changed(lambda x: x["first_success_oracle"]["stderr"].__setitem__("data", "WA=="))
        changed(lambda x: x.__setitem__("v", 1.0))
        for index, value in enumerate(cases):
            with self.subTest(index=index), self.assertRaises(Corruption):
                root_call_bytes(value)

    def test_root_id_reserves_double_dash_but_task_id_keeps_it(self):
        with self.assertRaises(Corruption):
            root_id("root--first")
        self.assertEqual(task_id("root--first"), "root--first")

    def test_in_process_call_budget_rejects_before_base64_decode(self):
        value = root_call()
        value["children"][0]["recipe"]["stdin"]["data"] = "A" * (1024 * 1024 + 1)
        with mock.patch("p1a2_model.base64.b64decode",
                        side_effect=AssertionError("decoder must not run")) as decode:
            with self.assertRaises(Corruption):
                root_call_bytes(value)
        decode.assert_not_called()

    def test_call_budget_counts_json_short_control_escapes_exactly(self):
        value = root_call()
        value["children"][0]["recipe"]["argv"] = ["\n" * 65536] * 3
        actual = root_call_bytes(value)
        self.assertLessEqual(len(actual), 1024 * 1024)
        self.assertIn(b"\\n\\n\\n", actual)


if __name__ == "__main__":
    unittest.main(verbosity=2)
